### ISSUE TITLE
Code not consistent with thesis

### ISSUE THREAD

**Issue by kazemia** [adebayoj/fairml#7]
Hi,
  In your thesis, somewhere you say that : four different algorithms, listed below, are run to rank the importance of all features. Each ranking algorithm produces a score for each feature. The four sets of scores obtained from the ranking algorithms are then aggregated into a combined score for each feature. The final ranking of a feature is determined by the combined score obtained. The results can then be scaled and ploted. The ranking algorithms consist of:
1.	 Iterative Orthogonal Feature Projection Algorithm (IOFP)
2.	minimum Redundancy, Maximum Relevance Feature Selection (mRMR)
3.	Least Absolute Shrinkage and Selection Operator (LASSO)
4.	Random Forest (RF)

However in the audit_model function which seems to be the main function, which is implemented in orthogonal_projection.py, you seem to only implement 1 and 2 and then return the results as 2 dictionaries. Am I correct and there is an inconsistency between the documentation and the code or have I misunderstood something?

**Comment by adebayoj** [comment]
Hi Kazemia,
Thanks for checking out the work. Here we only have implementations for 1 actually. We didn't include the implementations for 2-4 because these are all open source packages that can be used. The key new contribution of our work is the IOFP algorithm, so we assumed (probably wrongly) that people can find the implementations of the other methods publicly. For example, 3-4 come from the sklearn package.  For 2 (mRMR) there is this: https://github.com/fbrundu/pymrmr. 

We will be revamping this repo in about a month with significant updates that will include 2-4 as interfaces as well for replication.  Our updates will clear up this confusion. Happy to answer more questions.

**Comment by kazemia** [comment]
Thank you very much adebayoj. That made sense :)
